import type {
  RouteBundle,
  Trip,
  TripDocument,
  TripProviderAction,
  TripReminderCandidate,
  TripTask,
  TripTaskCommandResponse,
} from '../types/trip';

const now = '2026-06-06T09:00:00+10:00';
const todayMorning = '2026-06-06T10:00:00+10:00';
const todayAfternoon = '2026-06-06T15:00:00+10:00';
const tomorrowMorning = '2026-06-07T08:30:00+10:00';

export const sampleProviderActions: TripProviderAction[] = [
  {
    action_id: 'action-route-hotel-to-station',
    action_type: 'open_map_route',
    label: 'Open prepared route to Beijing South Railway Station',
    provider: 'apple_maps',
    reason: 'The train task needs a route with a confirmed origin and station destination.',
    deep_link: 'maps://?saddr=Qianmen%20Hotel&daddr=Beijing%20South%20Railway%20Station',
    fallback_url: 'https://maps.apple.com/?saddr=Qianmen%20Hotel&daddr=Beijing%20South%20Railway%20Station',
    requires_external_target: true,
    available: true,
    validation_status: 'ready',
  },
  {
    action_id: 'action-ticket-palace',
    action_type: 'open_ticket_site',
    label: 'Open official Palace Museum ticket page',
    provider: 'official_site',
    reason: 'Ticket confirmation unlocks the Day 2 morning activity.',
    url: 'https://example.com/palace-ticket',
    fallback_url: 'https://example.com/palace-ticket',
    requires_external_target: true,
    available: true,
    validation_status: 'ready',
  },
  {
    action_id: 'action-missing-route',
    action_type: 'open_map_route',
    label: 'Route action missing destination',
    provider: 'google_maps',
    reason: 'Used by tests to verify invalid provider actions do not become primary buttons.',
    requires_external_target: true,
    available: false,
    unavailable_reason: 'Destination is missing.',
    validation_status: 'unavailable',
  },
];

export const sampleTasks: TripTask[] = [
  {
    task_id: 'task-book-hotel',
    title: 'Confirm hotel beside a subway station',
    instruction: 'Keep the lodging clean, quiet, and within a short walk of Line 2 or Line 4.',
    category: 'lodging',
    status: 'pending',
    priority: 'high',
    phase_type: 'booking',
    due_at: todayMorning,
    provider_action_ids: [],
    reminder_enabled: true,
    reminder_offsets_minutes: [120, 30],
    created_at: now,
    updated_at: now,
  },
  {
    task_id: 'task-palace-ticket',
    title: 'Book Palace Museum morning entry',
    instruction: 'Use the official booking page and keep the confirmation in the document vault.',
    category: 'ticket',
    status: 'in_progress',
    priority: 'high',
    phase_type: 'preparation',
    due_at: todayAfternoon,
    provider_action_ids: ['action-ticket-palace'],
    reminder_enabled: true,
    reminder_offsets_minutes: [1440],
    created_at: now,
    updated_at: now,
  },
  {
    task_id: 'task-station-route',
    title: 'Leave hotel for Beijing South Railway Station',
    instruction: 'Open the prepared station route and leave buffer for luggage.',
    category: 'transport',
    status: 'pending',
    priority: 'medium',
    phase_type: 'departure_day',
    due_at: tomorrowMorning,
    provider_action_ids: ['action-route-hotel-to-station'],
    reminder_enabled: true,
    reminder_offsets_minutes: [90, 30],
    created_at: now,
    updated_at: now,
  },
  {
    task_id: 'task-upload-id',
    title: 'Save ID copies before ticket pickup',
    instruction: 'Attach ID references to the document vault. Sensitive files stay out of LLM prompts.',
    category: 'document',
    status: 'blocked',
    priority: 'medium',
    phase_type: 'preparation',
    due_at: todayAfternoon,
    blocked_reason: 'Hotel booking confirmation must be saved first.',
    provider_action_ids: [],
    reminder_enabled: false,
    created_at: now,
    updated_at: now,
  },
  {
    task_id: 'task-pack-raincoat',
    title: 'Pack lightweight raincoat',
    instruction: 'Weather risk is mild, but a compact layer keeps the Great Wall day flexible.',
    category: 'packing',
    status: 'completed',
    priority: 'low',
    phase_type: 'preparation',
    due_at: todayMorning,
    provider_action_ids: [],
    reminder_enabled: false,
    created_at: now,
    updated_at: now,
  },
];

export const sampleDocuments: TripDocument[] = [
  {
    document_id: 'doc-hotel-confirmation',
    category: 'hotel',
    title: 'Hotel booking confirmation',
    file_name: 'qianmen-hotel-confirmation.pdf',
    content_type: 'application/pdf',
    local_reference: 'file:///local/qianmen-hotel-confirmation.pdf',
    task_ids: ['task-book-hotel'],
    sensitive: false,
    prompt_excluded: true,
    created_at: now,
    updated_at: now,
  },
  {
    document_id: 'doc-id-copy',
    category: 'id_passport',
    title: 'Traveler ID copy',
    file_name: 'id-copy.pdf',
    content_type: 'application/pdf',
    local_reference: 'file:///local/id-copy.pdf',
    task_ids: ['task-upload-id'],
    sensitive: true,
    prompt_excluded: true,
    created_at: now,
    updated_at: now,
  },
  {
    document_id: 'doc-palace-ticket',
    category: 'ticket',
    title: 'Palace Museum ticket confirmation',
    file_name: 'palace-ticket.png',
    content_type: 'image/png',
    local_reference: 'file:///local/palace-ticket.png',
    task_ids: ['task-palace-ticket'],
    sensitive: false,
    prompt_excluded: true,
    created_at: now,
    updated_at: now,
  },
];

export const sampleTrip: Trip = {
  trip_id: 'trip-beijing-family-5d',
  tenant_id: 'tenant-demo',
  owner_user_id: 'user-demo',
  owner_account_mode: 'guest',
  is_sample: false,
  status: 'preparing',
  draft: {
    title: 'Beijing 5-Day Command Center Test Trip',
    summary: 'A compact test trip with lodging, tickets, transport, documents, reminders, and provider handoff.',
    destination: 'Beijing',
    start_date: '2026-06-07',
    end_date: '2026-06-11',
    warnings: ['Great Wall day needs weather and traffic buffer.'],
    evidence_refs: [
      {
        citation_id: 1,
        citation_line: '[1] Palace Museum official ticket page, https://example.com/palace-ticket',
      },
    ],
    milestones: [
      {
        milestone_id: 'milestone-day1-arrival',
        title: 'Arrive and check in',
        description: 'Settle near the subway before the first full sightseeing day.',
        day: 1,
        city: 'Beijing',
        date: '2026-06-07',
        start_time: '15:00',
        end_time: '17:00',
        citation_ids: [1],
        source: 'planning_answer',
      },
    ],
  },
  phases: [
    {
      phase_id: 'phase-booking',
      phase_type: 'booking',
      title: 'Booking',
      status: 'current',
      task_ids: ['task-book-hotel'],
    },
    {
      phase_id: 'phase-preparation',
      phase_type: 'preparation',
      title: 'Preparation',
      status: 'future',
      task_ids: ['task-palace-ticket', 'task-upload-id', 'task-pack-raincoat'],
    },
    {
      phase_id: 'phase-departure-day',
      phase_type: 'departure_day',
      title: 'Departure Day',
      status: 'future',
      task_ids: ['task-station-route'],
    },
  ],
  tasks: sampleTasks,
  provider_actions: sampleProviderActions,
  bookings: [
    {
      booking_id: 'booking-hotel-qianmen',
      category: 'hotel',
      title: 'Qianmen subway hotel',
      confirmation_code: 'HX-BJ-2026',
      provider: 'hotel_website',
      starts_at: '2026-06-07T15:00:00+08:00',
      ends_at: '2026-06-11T11:00:00+08:00',
      notes: 'Keep near Line 2 or Line 4.',
      task_ids: ['task-book-hotel'],
      created_at: now,
      updated_at: now,
    },
  ],
  documents: sampleDocuments,
};

export const sampleTaskCommand: TripTaskCommandResponse = {
  trip_id: sampleTrip.trip_id,
  now: [sampleTasks[0]],
  today: [sampleTasks[1]],
  upcoming: [sampleTasks[2]],
  blocked: [sampleTasks[3]],
  completed: [sampleTasks[4]],
  provider_actions: {
    'task-palace-ticket': [sampleProviderActions[1]],
    'task-station-route': [sampleProviderActions[0]],
  },
  generated_at: now,
};

export const sampleRouteBundle: RouteBundle = {
  route_id: 'route-hotel-to-station',
  label: 'Hotel to Beijing South Railway Station',
  mode: 'transit',
  origin: 'Qianmen Hotel, Beijing',
  destination: 'Beijing South Railway Station',
  waypoints: ['Line 2 transfer point'],
  planned_at: tomorrowMorning,
  primary_provider: 'apple_maps',
  fallback_url: 'https://maps.apple.com/?saddr=Qianmen%20Hotel&daddr=Beijing%20South%20Railway%20Station',
  provider_urls: {
    apple_maps: 'maps://?saddr=Qianmen%20Hotel&daddr=Beijing%20South%20Railway%20Station',
    google_maps:
      'https://www.google.com/maps/dir/?api=1&origin=Qianmen%20Hotel&destination=Beijing%20South%20Railway%20Station&travelmode=transit',
    mapbox: 'https://www.mapbox.com/search?query=Beijing%20South%20Railway%20Station',
  },
  confidence: 'high',
  handoff_ready: true,
  related_task_ids: ['task-station-route'],
};

export const sampleReminderCandidates: TripReminderCandidate[] = [
  {
    trip_id: sampleTrip.trip_id,
    task_id: 'task-book-hotel',
    title: 'Confirm hotel beside a subway station',
    body: 'Book lodging before the itinerary becomes execution-ready.',
    category: 'lodging',
    phase_type: 'booking',
    priority: 'high',
    due_at: todayMorning,
    reminder_at: '2026-06-06T08:00:00+10:00',
    offset_minutes: 120,
    quiet_hours_adjusted: false,
    tap_target: '/trips/trip-beijing-family-5d/tasks/task-book-hotel',
  },
  {
    trip_id: sampleTrip.trip_id,
    task_id: 'task-station-route',
    title: 'Leave hotel for Beijing South Railway Station',
    body: 'Open the prepared station route before leaving.',
    category: 'transport',
    phase_type: 'departure_day',
    priority: 'medium',
    due_at: tomorrowMorning,
    reminder_at: '2026-06-07T07:00:00+10:00',
    offset_minutes: 90,
    quiet_hours_adjusted: true,
    tap_target: '/trips/trip-beijing-family-5d/tasks/task-station-route',
  },
];

export const mobileTestingFixtureNames = [
  'sampleTrip',
  'sampleTaskCommand',
  'sampleRouteBundle',
  'sampleReminderCandidates',
  'sampleDocuments',
] as const;
